Removed community jdk's workflows and actions and created workflow to build jdk on ubuntu

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -1,132 +1,83 @@
-#
-# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
-# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
-#
-# This code is free software; you can redistribute it and/or modify it
-# under the terms of the GNU General Public License version 2 only, as
-# published by the Free Software Foundation.  Oracle designates this
-# particular file as subject to the "Classpath" exception as provided
-# by Oracle in the LICENSE file that accompanied this code.
-#
-# This code is distributed in the hope that it will be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
-# version 2 for more details (a copy is included in the LICENSE file that
-# accompanied this code).
-#
-# You should have received a copy of the GNU General Public License version
-# 2 along with this work; if not, write to the Free Software Foundation,
-# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
-#
-# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
-# or visit www.oracle.com if you need additional information or have any
-# questions.
-#
-
-name: 'Build (linux)'
+name: Build JDK on Linux
 
 on:
-  workflow_call:
-    inputs:
-      platform:
-        required: true
-        type: string
-      extra-conf-options:
-        required: false
-        type: string
-      make-target:
-        required: false
-        type: string
-        default: 'product-bundles test-bundles'
-      debug-levels:
-        required: false
-        type: string
-        default: '[ "debug", "release" ]'
-      apt-gcc-version:
-        required: true
-        type: string
-      apt-architecture:
-        required: false
-        type: string
-      apt-extra-packages:
-        required: false
-        type: string
+  pull_request:
+    branches: 
+    - main
 
 jobs:
-  build-linux:
-    name: build
+  build:
+
     runs-on: ubuntu-20.04
 
-    strategy:
-      fail-fast: false
-      matrix:
-        debug-level: ${{ fromJSON(inputs.debug-levels) }}
-        include:
-          - debug-level: debug
-            flags: --with-debug-level=fastdebug
-            suffix: -debug
-
     steps:
-      - name: 'Checkout the JDK source'
-        uses: actions/checkout@v3
+    - name: 'Checkout Source'
+      uses: actions/checkout@v3
+    
+    - name: 'Set up JDK 16'
+      uses: actions/setup-java@v3
+      with:
+        java-version: '16'
+        distribution: 'temurin'
+        java-package: jdk
+        
+    - name: 'Install jtreg'
+      run: sudo apt install jtreg
+      
+    - name: 'Install toolchain and dependencies'
+      run: |
+        # Install dependencies using apt-get
+        sudo apt-get update
+        sudo apt-get install --only-upgrade apt
+        sudo apt-get install build-essential libxrandr-dev libxtst-dev libcups2-dev libasound2-dev
+        
+    - name: 'Configure'
+      run: >
+        bash configure
+        --build=x86_64-unknown-linux-gnu
+        --openjdk-target=x86_64-unknown-linux-gnu
+        
+    - name: 'Make'
+      run: make images
+      
+    - name: 'Check for failure'
+      id: check
+      run: |
+        # Check for failure marker file
+        build_dir="$(ls -d build/*)"
+        if [[ -e $build_dir/build-failure ]]; then
+          # Collect relevant log files
+          mkdir failure-logs
+          cp \
+              $build_dir/spec.gmk \
+              $build_dir/build.log \
+              $build_dir/configure.log \
+              $build_dir/make-support/failure-summary.log \
+              $build_dir/make-support/failure-logs/* \
+              failure-logs/ 2> /dev/null || true
+          echo '::set-output name=failure::true'
+        fi
+      shell: bash
 
-      - name: 'Get the BootJDK'
-        id: bootjdk
-        uses: ./.github/actions/get-bootjdk
-        with:
-          platform: linux-x64
+    - name: 'Upload build logs'
+      uses: actions/upload-artifact@v3
+      with:
+        name: failure-logs-linux
+        path: failure-logs
+      if: steps.check.outputs.failure == 'true'
+      
+    - name: 'Check Version'
+      run: ./build/*/images/jdk/bin/java -version
+      
+    - name: 'Run Basic Tests'
+      run: make run-test-tier1
 
-      - name: 'Get JTReg'
-        id: jtreg
-        uses: ./.github/actions/get-jtreg
 
-      - name: 'Get GTest'
-        id: gtest
-        uses: ./.github/actions/get-gtest
 
-      - name: 'Set architecture'
-        id: arch
-        run: |
-          # Set a proper suffix for packages if using a different architecture
-          if [[ '${{ inputs.apt-architecture }}' != '' ]]; then
-            echo '::set-output name=suffix:::${{ inputs.apt-architecture }}'
-          fi
 
-      # Upgrading apt to solve libc6 installation bugs, see JDK-8260460.
-      - name: 'Install toolchain and dependencies'
-        run: |
-          # Install dependencies using apt-get
-          if [[ '${{ inputs.apt-architecture }}' != '' ]]; then
-            sudo dpkg --add-architecture ${{ inputs.apt-architecture }}
-          fi
-          sudo apt-get update
-          sudo apt-get install --only-upgrade apt
-          sudo apt-get install gcc-${{ inputs.apt-gcc-version }} g++-${{ inputs.apt-gcc-version }} libxrandr-dev${{ steps.arch.outputs.suffix }} libxtst-dev${{ steps.arch.outputs.suffix }} libcups2-dev${{ steps.arch.outputs.suffix }} libasound2-dev${{ steps.arch.outputs.suffix }} ${{ inputs.apt-extra-packages }}
-          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
 
-      - name: 'Configure'
-        run: >
-          bash configure
-          --with-conf-name=${{ inputs.platform }}
-          ${{ matrix.flags }}
-          --with-version-opt=${GITHUB_ACTOR}-${GITHUB_SHA}
-          --with-boot-jdk=${{ steps.bootjdk.outputs.path }}
-          --with-jtreg=${{ steps.jtreg.outputs.path }}
-          --with-gtest=${{ steps.gtest.outputs.path }}
-          --enable-jtreg-failure-handler
-          --with-zlib=system
-          ${{ inputs.extra-conf-options }}
 
-      - name: 'Build'
-        id: build
-        uses: ./.github/actions/do-build
-        with:
-          make-target: '${{ inputs.make-target }}'
-          platform: ${{ inputs.platform }}
-          debug-suffix: '${{ matrix.suffix }}'
 
-      - name: 'Upload bundles'
-        uses: ./.github/actions/upload-bundles
-        with:
-          platform: ${{ inputs.platform }}
-          debug-suffix: '${{ matrix.suffix }}'
+
+
+
